eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

server:
  port: 8008

spring:
  application:
    name: server-auth



jwt:
  expire: 3600
  pri-key:
    path: F:\IdeaProjects\cloud\springcloud-learning\server-auth\src\main\resources\pri.key
  pub-key:
    path: F:\IdeaProjects\cloud\springcloud-learning\server-auth\src\main\resources\pub.key