spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/geek_qi/AG-Config.git
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8002

