spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/itOcean/spring-cloud/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

server:
  port: 8002

