#server:
#  port: 8761
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 6060
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
#    prefer-ip-address: true
    ip-address: localhost
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/