eureka:
  instance:
      hostname: 10.0.0.86
  client:
    serviceUrl:
      defaultZone: http://localhost:6060/eureka/
#      http://huaxin:123456@10.0.0.97:8000/eureka/
server:
  port: 6003
spring:
  application:
    name: service-ribbon-1