eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6060/eureka/
server:
  port: 6063
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /a/**
      serviceId: service-ribbon-1
    api-b:
      path: /b/**
      serviceId: service-feign