eureka:
  instance:
    hostname: 10.0.0.86
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:6060/eureka/
#      http://huaxin:123456@10.0.0.97:8000/eureka/   http://localhost:6060/eureka/
server:
  port: 6001

spring:
  application:
    name: eureka-client-1