eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

server:
  port: 8008

spring:
  application:
    name: server-auth
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud
    username: root
    password: wangzhang
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 1000



jwt:
  expire: 3600
  pri-key:
    path: F:\IdeaProjects\cloud\springcloud-learning\server-auth\src\main\resources\pri.key
  pub-key:
    path: F:\IdeaProjects\cloud\springcloud-learning\server-auth\src\main\resources\pub.key